      - name: Case 01 - contoh resmi
        id: case-01
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Case 01 - contoh resmi
          setup-command: gcc -std=c11 -O2 -Wall -Wextra -o soal2 soal2.c
          command: ./soal2
          input: "5 4 2 7 3 6"
          expected-output: |-
            MIN_DIFF 3
            CUT 2 3
          comparison-method: exact
          timeout: 2
          max-score: 10

      - name: Case 07 - ada elemen nol
        id: case-07
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Case 07 - ada elemen nol
          setup-command: gcc -std=c11 -O2 -Wall -Wextra -o soal2 soal2.c
          command: ./soal2
          input: "5 0 0 10 0 0"
          expected-output: |-
            MIN_DIFF 10
            CUT 1 2
          comparison-method: exact
          timeout: 2
          max-score: 10

      - name: Case 08 - banyak tie
        id: case-08
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Case 08 - banyak tie
          setup-command: gcc -std=c11 -O2 -Wall -Wextra -o soal2 soal2.c
          command: ./soal2
          input: "5 2 2 2 2 2"
          expected-output: |-
            MIN_DIFF 2
            CUT 1 3
          comparison-method: exact
          timeout: 2
          max-score: 10

      - name: Case 09 - distribusi hampir seimbang
        id: case-09
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Case 09 - distribusi hampir seimbang
          setup-command: gcc -std=c11 -O2 -Wall -Wextra -o soal2 soal2.c
          command: ./soal2
          input: "7 3 1 2 2 3 1 2"
          expected-output: |-
            MIN_DIFF 2
            CUT 2 4
          comparison-method: exact
          timeout: 2
          max-score: 10

      - name: Case 10 - dominasi awal array
        id: case-10
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Case 10 - dominasi awal array
          setup-command: gcc -std=c11 -O2 -Wall -Wextra -o soal2 soal2.c
          command: ./soal2
          input: "5 10 1 1 1 1"
          expected-output: |-
            MIN_DIFF 8
            CUT 1 3
          comparison-method: exact
          timeout: 2
          max-score: 10
